# Generated by Django 6.0 on 2026-07-04 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPaper',
            fields=[
                ('paper_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('paper_type', models.CharField(choices=[('RTP', 'RTP'), ('PYQ', 'PYQ'), ('MOCK', 'MOCK')], max_length=20)),
                ('total_questions', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_papers', to='syllabus.chapter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_papers', to='syllabus.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_papers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_number', models.CharField(max_length=20)),
                ('sub_question_label', models.CharField(blank=True, max_length=10, null=True)),
                ('question_content', models.TextField()),
                ('question_text', models.TextField()),
                ('answer_content', models.TextField()),
                ('answer_text', models.TextField()),
                ('question_type', models.CharField(default='UNIDENTIFIED', max_length=30)),
                ('marks', models.PositiveIntegerField(blank=True, null=True)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='syllabus.chapter')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='documents.document')),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_questions', to='papers.question')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedPaperQuestion',
            fields=[
                ('generated_paper_question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_order', models.PositiveIntegerField()),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_questions', to='papers.generatedpaper')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_mappings', to='papers.question')),
            ],
        ),
        migrations.AddIndex(
            model_name='generatedpaper',
            index=models.Index(fields=['user'], name='idx_generated_paper_user'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['document'], name='idx_question_document'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['chapter'], name='idx_question_chapter'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['parent_question'], name='idx_question_parent'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type'], name='idx_question_type'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('document', 'question_number', 'sub_question_label'), name='unique_question_per_document'),
        ),
        migrations.AddConstraint(
            model_name='generatedpaperquestion',
            constraint=models.UniqueConstraint(fields=('paper', 'question_order'), name='unique_paper_question_order'),
        ),
    ]
