# Generated by Django 6.0 on 2026-07-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_alter_question_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
