# Generated by Django 5.2.15 on 2026-07-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('papers', '0003_question_instruction_type'),
        ('syllabus', '0003_alter_subject_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_question_per_document',
        ),
        migrations.AddField(
            model_name='question',
            name='hierarchy_key',
            field=models.CharField(blank=True, db_index=True, max_length=512, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('document', 'hierarchy_key'), name='unique_question_hierarchy_per_document'),
        ),
    ]
