# Generated by Django 5.2.15 on 2026-08-09 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_remove_question_unique_question_per_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedpaperquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_mappings', to='papers.question'),
        ),
    ]
