# Generated by Django 5.2.17 on 2026-08-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_alter_generatedpaperquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sub_question_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
