# Generated by Django 6.0 on 2026-07-03 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('RTP', 'RTP'), ('PYQ', 'PYQ'), ('MOCK', 'MOCK')], max_length=10)),
                ('paper_year', models.PositiveIntegerField()),
                ('paper_session', models.CharField(blank=True, max_length=20, null=True)),
                ('storage_path', models.TextField(editable=False)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('extraction_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='syllabus.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['subject'], name='idx_document_subject'), models.Index(fields=['document_type'], name='idx_document_type')],
            },
        ),
    ]
