# Generated by Django 5.2.15 on 2026-07-03 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('exam_level', models.CharField(choices=[('Foundation', 'Foundation'), ('Intermediate', 'Intermediate'), ('Final', 'Final')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=100)),
                ('chapter_order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='syllabus.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject', 'chapter_name'), name='unique_subject_chapter')],
            },
        ),
    ]
