# Generated by Django 6.0 on 2026-07-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterKeyword',
            fields=[
                ('chapter_keyword_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keywords', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_record', to='syllabus.chapter')),
            ],
        ),
    ]
