# Generated by Django 5.2.15 on 2026-07-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_chapterkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name', 'exam_level'), name='unique_subject_name_exam_level'),
        ),
    ]
